name: Test & Lint
on:
   push:

jobs:
   test:
      runs-on: ubuntu-20.04
      steps:
         - uses: actions/checkout@v4

         - uses: pnpm/action-setup@v4
           with:
              run_install: |
                 - recursive: true
                   args: [--frozen-lockfile, --strict-peer-dependencies]

         - uses: actions/setup-node@v4
           with:
              node-version: 18
              cache: pnpm
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         - run: pnpm run test
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
